config/routes.rb
Rails.application.routes.draw do

  root "dostep#index"
  get 'admin' ,:to=>"dostep#index"

  resources :grupas

  resources :kursies

  resources :kursy_zamowienies

  resources :zamowienies

  resources :uzytkowniks

end

app/controllers/kursy_zamowienies_controller.rb
class KursyZamowieniesController < ApplicationController
  layout 'admin'
  before_action :set_kursy_zamowieny, only: [:show, :edit, :update, :destroy]

  # GET /kursy_zamowienies
  # GET /kursy_zamowienies.json
  def index
    @kursy_zamowienies = KursyZamowienie.all
  end

  # GET /kursy_zamowienies/1
  # GET /kursy_zamowienies/1.json
  def show
  end

  # GET /kursy_zamowienies/new
  def new
    @kursy_zamowieny = KursyZamowienie.new
  end

  # GET /kursy_zamowienies/1/edit
  def edit
  end

  # POST /kursy_zamowienies
  # POST /kursy_zamowienies.json
  def create
    @kursy_zamowieny = KursyZamowienie.new(kursy_zamowieny_params)

    respond_to do |format|
      if @kursy_zamowieny.save
        format.html { redirect_to @kursy_zamowieny, notice: 'Kursy zamowienie was successfully created.' }
        format.json { render :show, status: :created, location: @kursy_zamowieny }
      else
        format.html { render :new }
        format.json { render json: @kursy_zamowieny.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kursy_zamowienies/1
  # PATCH/PUT /kursy_zamowienies/1.json
  def update
    respond_to do |format|
      if @kursy_zamowieny.update(kursy_zamowieny_params)
        format.html { redirect_to @kursy_zamowieny, notice: 'Kursy zamowienie was successfully updated.' }
        format.json { render :show, status: :ok, location: @kursy_zamowieny }
      else
        format.html { render :edit }
        format.json { render json: @kursy_zamowieny.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kursy_zamowienies/1
  # DELETE /kursy_zamowienies/1.json
  def destroy
    @kursy_zamowieny.destroy
    respond_to do |format|
      format.html { redirect_to kursy_zamowienies_url, notice: 'Kursy zamowienie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kursy_zamowieny
      @kursy_zamowieny = KursyZamowienie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kursy_zamowieny_params
      params.require(:kursy_zamowieny).permit(:zamowienie_id, :kursy_id)
    end
end

app/helpers/kursy_zamowienies_helper.rb
module KursyZamowieniesHelper
end

app/views/kursy_zamowienies/_form.html.erb
<table class="table table-striped">
<%= form_for(@kursy_zamowieny) do |f| %>
  <% if @kursy_zamowieny.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kursy_zamowieny.errors.count, "error") %> prohibited this kursy_zamowieny from being saved:</h2>

      <ul>
      <% @kursy_zamowieny.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zamowienie_id %><br>
    <%= f.number_field :zamowienie_id, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :kursy_id %><br>
    <%= f.number_field :kursy_id , :class => 'form-control'%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</table>

app/views/kursy_zamowienies/edit.html.erb
<h1>Editing kursy_zamowieny</h1>

<%= render 'form' %>

<%= link_to 'Show', @kursy_zamowieny %> |
<%= link_to 'Back', kursy_zamowienies_path %>

app/views/kursy_zamowienies/index.html.erb
<div class="hero-unit">
  

<h1>Listing kursy_zamowienies</h1>

<table>
  <thead>
    <tr>
      <th>Zamowienie</th>
      <th>Kursy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kursy_zamowienies.each do |kursy_zamowieny| %>
      <tr>
        <td><%= kursy_zamowieny.zamowienie_id %></td>
        <td><%= kursy_zamowieny.kursy_id %></td>
        <td><%= link_to 'Show', kursy_zamowieny %></td>
        <td><%= link_to 'Edit', edit_kursy_zamowieny_path(kursy_zamowieny) %></td>
        <td><%= link_to 'Destroy', kursy_zamowieny, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kursy zamowienie', new_kursy_zamowieny_path %>
</div>

app/views/kursy_zamowienies/new.html.erb
<h1>New kursy_zamowieny</h1>

<%= render 'form' %>

<%= link_to 'Back', kursy_zamowienies_path %>

app/views/kursy_zamowienies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zamowienie:</strong>
  <%= @kursy_zamowieny.zamowienie_id %>
</p>

<p>
  <strong>Kursy:</strong>
  <%= @kursy_zamowieny.kursy_id %>
</p>

<%= link_to 'Edit', edit_kursy_zamowieny_path(@kursy_zamowieny) %> |
<%= link_to 'Back', kursy_zamowienies_path %>