config/routes.rb
Rails.application.routes.draw do

  root "dostep#index"
  get 'admin' ,:to=>"dostep#index"

  resources :grupas

  resources :kursies

  resources :kursy_zamowienies

  resources :zamowienies

  resources :uzytkowniks

end

app/models/uzytkownik.rb
class Uzytkownik < ActiveRecord::Base
 
  EMAIL_REGEX = /\A[a-z0-0._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
  
  validates :imie, :presence => true
  validates :nazwisko, :presence => true
  validates :login, :length => {:within =>3..20, :messege => "login musi być dluzszy niz 3 znaki i krotszy niz 20 znakow"}, :uniqueness => true
  validates :email, :presence => true, :length => {:maximum => 100}, :format => EMAIL_REGEX, :confirmation => true
  has_many :zamowienies
  has_many :grupas
end

app/controllers/uzytkowniks_controller.rb
class UzytkowniksController < ApplicationController
  layout 'admin'
  before_action :set_uzytkownik, only: [:show, :edit, :update, :destroy]

  # GET /uzytkowniks
  # GET /uzytkowniks.json
  def index
    @uzytkowniks = Uzytkownik.all
  end

  # GET /uzytkowniks/1
  # GET /uzytkowniks/1.json
  def show
  end

  # GET /uzytkowniks/new
  def new
    @uzytkownik = Uzytkownik.new
  end

  # GET /uzytkowniks/1/edit
  def edit
  end

  # POST /uzytkowniks
  # POST /uzytkowniks.json
  def create
    @uzytkownik = Uzytkownik.new(uzytkownik_params)

    respond_to do |format|
      if @uzytkownik.save
        format.html { redirect_to @uzytkownik, notice: 'Uzytkownik was successfully created.' }
        format.json { render :show, status: :created, location: @uzytkownik }
      else
        format.html { render :new }
        format.json { render json: @uzytkownik.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uzytkowniks/1
  # PATCH/PUT /uzytkowniks/1.json
  def update
    respond_to do |format|
      if @uzytkownik.update(uzytkownik_params)
        format.html { redirect_to @uzytkownik, notice: 'Uzytkownik was successfully updated.' }
        format.json { render :show, status: :ok, location: @uzytkownik }
      else
        format.html { render :edit }
        format.json { render json: @uzytkownik.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uzytkowniks/1
  # DELETE /uzytkowniks/1.json
  def destroy
    @uzytkownik.destroy
    respond_to do |format|
      format.html { redirect_to uzytkowniks_url, notice: 'Uzytkownik was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uzytkownik
      @uzytkownik = Uzytkownik.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uzytkownik_params
      params.require(:uzytkownik).permit(:imie, :nazwisko, :login, :password_digest, :email)
    end
end

app/helpers/uzytkowniks_helper.rb
module UzytkowniksHelper
end

app/views/uzytkowniks/_form.html.erb
<table class="table table-striped">
<%= form_for(@uzytkownik) do |f| %>
  <% if @uzytkownik.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uzytkownik.errors.count, "error") %> prohibited this uzytkownik from being saved:</h2>

      <ul>
      <% @uzytkownik.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :imie %><br>
    <%= f.text_field :imie , :class => 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :nazwisko %><br>
    <%= f.text_field :nazwisko , :class => 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login , :class => 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest , :class => 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email , :class => 'form-control'%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  </table>

app/views/uzytkowniks/edit.html.erb
<div class="hero-unit">
<h1>Edycja użytkownika</h1>

<%= render 'form' %>

<%= link_to 'Show', @uzytkownik , :class => 'btn btn-mini btn-primary'%> |
<%= link_to 'Back', uzytkowniks_path , :class => 'btn btn-mini btn-warning'%>
</div>

app/views/uzytkowniks/index.html.erb
<div class="hero-unit">
<h1>Spis użytkowników</h1>

<table class ="table table-striped">
  <thead>
    <tr class="info">
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>Login</th>
      <th>Password digest</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uzytkowniks.each do |uzytkownik| %>
      <tr>
        <td><%= uzytkownik.imie %></td>
        <td><%= uzytkownik.nazwisko %></td>
        <td><%= uzytkownik.login %></td>
        <td><%= uzytkownik.password_digest %></td>
        <td><%= uzytkownik.email %></td>
        <td><%= link_to 'Show', uzytkownik , :class => 'btn btn-mini btn-default'%></td>
        <td><%= link_to 'Edit', edit_uzytkownik_path(uzytkownik), :class => 'btn btn-mini btn-primary'%></td>
        <td><%= link_to 'Destroy', uzytkownik, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uzytkownik', new_uzytkownik_path, :class => 'btn btn-mini btn-primary' %>
<%= link_to("Powrót", {:controller => 'dostep'}, :class => 'btn btn-default')%>
</div>

app/views/uzytkowniks/new.html.erb
<div class="hero-unit">
  <h1>New uzytkownik</h1>

<%= render 'form' %>

<%= link_to 'Back', uzytkowniks_path, :class => 'btn btn-mini btn-warning' %>
</div>

app/views/uzytkowniks/show.html.erb
<div class="hero-unit">
<p id="notice"><%= notice %></p>
<table class ="table table-striped">
<p>
  <strong>Imie:</strong>
  <%= @uzytkownik.imie %>
</p>

<p>
  <strong>Nazwisko:</strong>
  <%= @uzytkownik.nazwisko %>
</p>

<p>
  <strong>Login:</strong>
  <%= @uzytkownik.login %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @uzytkownik.password_digest %>
</p>

<p>
  <strong>Email:</strong>
  <%= @uzytkownik.email %>
</p>
  </table>

<%= link_to 'Edit', edit_uzytkownik_path(@uzytkownik), :class => 'btn btn-mini btn-primary' %> |
<%= link_to 'Back', uzytkowniks_path , :class => 'btn btn-mini btn-warning'%>

  
  
  
  </div>