config/routes.rb
Rails.application.routes.draw do

  root "dostep#index"
  get 'admin' ,:to=>"dostep#index"

  resources :grupas

  resources :kursies

  resources :kursy_zamowienies

  resources :zamowienies

  resources :uzytkowniks

end

app/models/grupa.rb
class Grupa < ActiveRecord::Base
  validates :kurs_id, :persence => true
  validates :uzytkownik_id, :persence => true
  has_many :uzytkowniks
  belongs_to :kursie
end

app/controllers/grupas_controller.rb
class GrupasController < ApplicationController
  layout 'admin'
  before_action :set_grupa, only: [:show, :edit, :update, :destroy]

  # GET /grupas
  # GET /grupas.json
  def index
    @grupas = Grupa.all
  end

  # GET /grupas/1
  # GET /grupas/1.json
  def show
  end

  # GET /grupas/new
  def new
    @grupa = Grupa.new
  end

  # GET /grupas/1/edit
  def edit
  end

  # POST /grupas
  # POST /grupas.json
  def create
    @grupa = Grupa.new(grupa_params)

    respond_to do |format|
      if @grupa.save
        format.html { redirect_to @grupa, notice: 'Grupa was successfully created.' }
        format.json { render :show, status: :created, location: @grupa }
      else
        format.html { render :new }
        format.json { render json: @grupa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupas/1
  # PATCH/PUT /grupas/1.json
  def update
    respond_to do |format|
      if @grupa.update(grupa_params)
        format.html { redirect_to @grupa, notice: 'Grupa was successfully updated.' }
        format.json { render :show, status: :ok, location: @grupa }
      else
        format.html { render :edit }
        format.json { render json: @grupa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupas/1
  # DELETE /grupas/1.json
  def destroy
    @grupa.destroy
    respond_to do |format|
      format.html { redirect_to grupas_url, notice: 'Grupa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupa
      @grupa = Grupa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grupa_params
      params.require(:grupa).permit(:kurs_id, :uzytkownik_id)
    end
end

app/helpers/grupas_helper.rb
module GrupasHelper
end

app/views/grupas/_form.html.erb
<table class="table table-striped">
  

<%= form_for(@grupa) do |f| %>
  <% if @grupa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grupa.errors.count, "error") %> prohibited this grupa from being saved:</h2>

      <ul>
      <% @grupa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kurs_id %><br>
    <%= f.number_field :kurs_id, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :uzytkownik_id %><br>
    <%= f.number_field :uzytkownik_id, :class => 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  </table>

app/views/grupas/edit.html.erb
<div class="hero-unit">
<h1>EEdycja grupy</h1>

<%= render 'form' %>

<%= link_to 'Show', @grupa , :class => 'btn btn-mini btn-primary'%> |
<%= link_to 'Back', grupas_path , :class => 'btn btn-mini btn-warning'%>
</div>

app/views/grupas/index.html.erb
<div class="hero-unit">
  

<h1>Spis grup</h1>

<table class ="table table-striped">
  <thead>
    <tr class="info">
      <th>Kurs</th>
      <th>Uzytkownik</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grupas.each do |grupa| %>
      <tr>
        <td><%= grupa.kurs_id %></td>
        <td><%= grupa.uzytkownik_id %></td>
        <td><%= link_to 'Show', grupa , :class => 'btn btn-mini btn-default'%></td>
        <td><%= link_to 'Edit', edit_grupa_path(grupa) , :class => 'btn btn-mini btn-primary'%></td>
        <td><%= link_to 'Destroy', grupa, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-mini btn-danger'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grupa', new_grupa_path , :class => 'btn btn-mini btn-primary'%>
  <%= link_to("Powrót", {:controller => 'dostep'}, :class => 'btn btn-warning')%>
  </div>

app/views/grupas/new.html.erb
<div class="hero-unit">
<h1>Nowa grupa</h1>

<%= render 'form' %>

<%= link_to 'Back', grupas_path, :class => 'btn btn-mini btn-warning' %>
</div>

app/views/grupas/show.html.erb
<div class="hero-unit">
<p id="notice"><%= notice %></p>

<p>
  <strong>Kurs:</strong>
  <%= @grupa.kurs_id %>
</p>

<p>
  <strong>Uzytkownik:</strong>
  <%= @grupa.uzytkownik_id %>
</p>

<%= link_to 'Edit', edit_grupa_path(@grupa), :class => 'btn btn-mini btn-primary' %> |
<%= link_to 'Back', grupas_path, :class => 'btn btn-mini btn-warning' %>

  
  </div>