config/routes.rb
Rails.application.routes.draw do

  root "dostep#index"
  get 'admin' ,:to=>"dostep#index"

  resources :grupas

  resources :kursies

  resources :kursy_zamowienies

  resources :zamowienies

  resources :uzytkowniks

end

app/models/kursy.rb
class Kursy < ActiveRecord::Base
  validates :nazwa, :persence => true
  validates :cena_w_zl, :persence => true
  belongs_to :grupa
  has_many :kursy_zamowienies
end

app/controllers/kursies_controller.rb
class KursiesController < ApplicationController
  layout 'admin'
  before_action :set_kursy, only: [:show, :edit, :update, :destroy]

  # GET /kursies
  # GET /kursies.json
  def index
    @kursies = Kursy.all
  end

  # GET /kursies/1
  # GET /kursies/1.json
  def show
  end

  # GET /kursies/new
  def new
    @kursy = Kursy.new
  end

  # GET /kursies/1/edit
  def edit
  end

  # POST /kursies
  # POST /kursies.json
  def create
    @kursy = Kursy.new(kursy_params)

    respond_to do |format|
      if @kursy.save
        format.html { redirect_to @kursy, notice: 'Kursy was successfully created.' }
        format.json { render :show, status: :created, location: @kursy }
      else
        format.html { render :new }
        format.json { render json: @kursy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kursies/1
  # PATCH/PUT /kursies/1.json
  def update
    respond_to do |format|
      if @kursy.update(kursy_params)
        format.html { redirect_to @kursy, notice: 'Kursy was successfully updated.' }
        format.json { render :show, status: :ok, location: @kursy }
      else
        format.html { render :edit }
        format.json { render json: @kursy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kursies/1
  # DELETE /kursies/1.json
  def destroy
    @kursy.destroy
    respond_to do |format|
      format.html { redirect_to kursies_url, notice: 'Kursy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kursy
      @kursy = Kursy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kursy_params
      params.require(:kursy).permit(:nazwa, :cena_w_zl)
    end
end

app/helpers/kursies_helper.rb
module KursiesHelper
end

app/views/kursies/_form.html.erb
<table class="table table-striped">
<%= form_for(@kursy) do |f| %>
  <% if @kursy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kursy.errors.count, "error") %> prohibited this kursy from being saved:</h2>

      <ul>
      <% @kursy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nazwa %><br>
    <%= f.text_field :nazwa , :class => 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :cena_w_zl %><br>
    <%= f.number_field :cena_w_zl , :class => 'form-control'%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</table>

app/views/kursies/edit.html.erb
<div class="hero-unit">
<h1>Edycja kursów</h1>

<%= render 'form' %>

<%= link_to 'Show', @kursy , :class => 'btn btn-mini btn-primary'%> |
<%= link_to 'Back', kursies_path , :class => 'btn btn-mini btn-warning'%>
</div>

app/views/kursies/index.html.erb
<div class="hero-unit">
  

<h1>Spis kursów</h1>

<table class ="table table-striped">
  <thead>
    <tr class="info">
      <th>Nazwa</th>
      <th>Cena w zl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kursies.each do |kursy| %>
      <tr>
        <td><%= kursy.nazwa %></td>
        <td><%= kursy.cena_w_zl %></td>
        <td><%= link_to 'Show', kursy, :class => 'btn btn-mini btn-default' %></td>
        <td><%= link_to 'Edit', edit_kursy_path(kursy), :class => 'btn btn-mini btn-primary' %></td>
        <td><%= link_to 'Destroy', kursy, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kursy', new_kursy_path, :class => 'btn btn-mini btn-primary' %>
  <%= link_to("Powrót", {:controller => 'dostep'}, :class => 'btn btn-default')%>
  </div>

app/views/kursies/new.html.erb
<div class="hero-unit">
<h1>Nowy kurs</h1>

<%= render 'form' %>

<%= link_to 'Back', kursies_path, :class => 'btn btn-mini btn-warning'%>
</div>

app/views/kursies/show.html.erb
<div class="hero-unit">
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazwa:</strong>
  <%= @kursy.nazwa %>
</p>

<p>
  <strong>Cena w zl:</strong>
  <%= @kursy.cena_w_zl %>
</p>

<%= link_to 'Edit', edit_kursy_path(@kursy) , :class => 'btn btn-mini btn-primary'%> |
<%= link_to 'Back', kursies_path , :class => 'btn btn-mini btn-warning'%>
</div>